Module6 task1
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #10
Opened 2021-09-02 07:00 UTC by Nastasiya-Kam

У меня каждое открытие попапа создаёт новый компонент. И изменения, которые не были сохранены в комментарии, пропадают

Но разве я не храню данные о пути к картинке-смайлу, введённый текст пользователя в _data, почему они пропадают?

2021-09-02 12:57 UTC, raccoonlemon requested changes
Кажется, ты ориентировалась в демо-проекте на форму редактирования задачи, но у нас тут больше подходит форма создания новой задачи.

Вот какой из них примерно список задач получается из комментариев к коду:

- Нужно исправить рендер блока с комментариями. Чтобы его отрисовывал презентер попапа.

- Компонент FilmComments должен наследоваться от SmartView.

- У компонента FilmComments должен быть метод типа setOnCommitSubmitHandler(callback)
Типа такого:

  setOnCommitSubmitHandler(callback){
    this._callback.handleCommentSubmit = callback;
    this.getElement()
      .querySelector('.film-details__comment-input')
      .addEventListener('keydown', this._handleCommentSubmit);
  }

  _handleCommentSubmit(evt){
    if (!isCtrlEnterEvent(evt)) {return;}
    evt.preventDefault();
    this._callback.handleCommentSubmit(this._data);
  }

Когда мы вызовем его, тому кто вызвал должны вернуться текущие данные формы. 
this._data = {
  emotion: 'smile'
  text: 'text',
};

Вот. Давай это переделаем, я думаю это решит большую часть проблем.
Если вдруг что-то сложно или непонятно - можем вместе не консультации разобрать.

2021-09-02 12:57 UTC, raccoonlemon commented on src/presenter/film-details.js
> +  // ?чтобы в презентере обращаться не к методу this._filmDetailsPresenter.isOpened(), а просто к переменной this._filmDetailsPresenter.isOpen?
Угу, можно так =)

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +    }, true);
Для чего нужен isEditCommentExist?

И в целом лучше работать отдельно со списком фильмов и отдельно с комментариями.
Отсюда мы должны вернуть только комментарий с id фильма. 

Типа такого:
{text: 'comment text', emotion: 'smile', 'filmId': 2}

Нам не нужно парсить целый фильм в данные и обратно. Нам вообще по сути ничего парсить не нужно. У нас изначально будет this._data = {text: '', emotion: ''}. Мы ее просто заполняем. 

Посмотри часть ТЗ, где описывается взаимодействие с сервером. В частности отправку комментария.

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +    this.getElement().querySelector('.film-details__emoji-list').addEventListener('click', this._onEmojiClick);
Лучше это событие повесить на onChange для '.film-details__emoji-list'. Когда мы щелкаем на картинку, которая обернута в label - у нас как раз это событие и вызовется. И в обработчике взять evt.target.value.

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +        <div class="film-details__bottom-container">${new FilmCommentsView(comments, isEditCommentExist, newComment).getTemplate()}</div>
Идея хорошая вынести комментарии в отдельный view. Но такая реализация не подходит. 
Получается, что ты просто взяла из FilmCommentsView шаблон разметки. Это все равно что его просто в строке хранить.

Это нужно делать в презентере FilmDetails. 
По аналогии как мы в главном презентере рендерим кусочки доски.
_renderList
_renderSort
...

и тут так же надо разбить, что-то вроде:
_renderPopup
_renderFilmDetails
_renderFilmComments

и тогда будет не 
`class FilmDetails extends SmartView {`
а так
`class FilmComments extends SmartView {`

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/card-film.js
> +  }
Я думаю, нам это совсем не нужно в этом проекте. Т.к мы не изменяем существующий объект. Мы просто добавляем новый комментарий. Мы его даже редактировать после добавления не можем.

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +  }
Тут скорее будет что-то типа 
  ```
_onEmojiClick(evt){
    if (evt.target.value === this._data.emotion) {
      return;
    }

    this.updateData({
      emotion: evt.target.value,
    });
  }

  _commentChangeHandler(evt){
    this.updateData({
      text: evt.target.value,
    }, true);
  }
```

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +    this._data = FilmDetails.parseFilmToData(film);
Тут можно проще:

```
const initialComment = {
  emotion: null,
  text: '',
};
```
...
`this._data = initialComment ;`

2021-09-02 12:57 UTC, raccoonlemon commented on src/view/film-details.js
> +    this._data = FilmDetails.parseFilmToData(film);
Наверное, аналогией из демо-проекта будет не форма редактирования, а форма создания новой задачи.

2021-09-02 12:59 UTC, raccoonlemon commented
> У меня каждое открытие попапа создаёт новый компонент. И изменения, которые не были сохранены в комментарии, пропадают
> 
> Но разве я не храню данные о пути к картинке-смайлу, введённый текст пользователя в _data, почему они пропадают?
> 
> 🎓 [Обновление века (часть 1)](https://up.htmlacademy.ru/ecmascript/15/user/1608929/tasks/10)
> 
> 💥 https://htmlacademy-ecmascript.github.io/1608929-cinemaddict-15/10/

По идее при закрытии попапа это нормально, что комментарий пропадает. Если я вдруг неправильно поняла вопрос, поправь меня, пожалуйста.

2021-09-02 13:32 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    }, true);
isEditCommentExist завела, чтобы рисовать картинку или нет. Потому что когда комментарий никто не создаёт, то картинки в большом окошке нет, и как я понимаю, тэг имг тоже не нужен

Отсюда флаг, создаётся ли комментарий, чтобы понимать, нужно ли рисовать этот имг или нет

2021-09-02 13:35 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    }, true);
считала новый комментарий частью объекта фильма, т.к. и комментарий относится к конкретному фильму, а не ко всем. Была мысль, сделать просто объект как ты тут говоришь (только без id фильма). Сложно_) после проссмотра ролика понимала что парсить, но по сути у себя ничего дельного не нашла. isEditCommentExist высосан из пальца_)

2021-09-03 06:21 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    }, true);
сделала отдельно объект 
```
_data {
  emotion: '',
  comment: '',
  isEmpty: '',
}
```

isEmpty нужен как флаг: рисовать картинку в окошке большом или нет

2021-09-03 06:22 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +        <div class="film-details__bottom-container">${new FilmCommentsView(comments, isEditCommentExist, newComment).getTemplate()}</div>
убрала

2021-09-03 06:22 UTC, Nastasiya-Kam commented on src/view/card-film.js
> +  }
убрала

2021-09-03 06:30 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    this._data = FilmDetails.parseFilmToData(film);
переделала переменную с комментом, из film-details убрала совсем

2021-09-03 06:32 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    this.getElement().querySelector('.film-details__emoji-list').addEventListener('click', this._onEmojiClick);
Вот тут не очень поняла, при первой попытке он возвращает значение input, а я же хочу забрать путь у картинки. Посмотрю попозже ещё раз про событие change, на что оно реагирует и что возвращает

2021-09-03 06:33 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +  }
переделала типа того тока для click. С value события change пока не разобралась (см.выше коммент)

2021-09-03 17:55 UTC, raccoonlemon approved these changes
Ураа, теперь работает =)

Еще как идея - в папке view завести папки 
- что-то типа film-details, туда сложить все что относится к попапу (комменты, детали, контроллы)
- common - туда сложить abstract и smart

2021-09-03 17:55 UTC, raccoonlemon commented on src/presenter/film-board.js
> +      });
Красивое =)

2021-09-03 17:55 UTC, raccoonlemon commented on src/view/card-film.js
> +  }
Хм, вроде написано что убрала, но осталось parseFilmToData и parseDataToFilm. Может что-то не запушила?
В этом компоненте оно нам точно не нужно. У нас нет формы редактирования. И этот компонент не SmartView.

2021-09-03 17:55 UTC, raccoonlemon commented on src/view/film-comments.js
> +    };
Можно вместо isEmpty сделать начальное значение emotion: null и проверить на if (emotion)...

2021-09-03 17:55 UTC, raccoonlemon commented on src/view/film-comments.js
>      </div>
Тут заметила что смайлы вывелись через запятую. Нужно добавить join (createEmojiList(EMOJI).join('')).

2021-09-03 17:55 UTC, raccoonlemon commented on src/presenter/film-details.js
> +  }
Вспомнила твой вопрос (кажется был в прошлом задании), что можно ли заменить на просто this.isOpen и так использовать. Я там написала что можно.

Но потом еще подумала - лучше оставить так.

Т.к если дать доступ к this.isOpen, то создается ложное впечатление что можно извне вызвать presenter.isOpen = true, но так ведь не будет работать. А presenter.isOpened() - то понятно, что это только для чтения.

2021-09-03 17:55 UTC, raccoonlemon commented on src/presenter/film-details.js
> +    this.renderControls(this._film);
В компоненте this._filmDetailsComponent завести метод типа getContainer/getBottomContainer.
Презентер не должен знать как там _filmDetailsComponent внутри устроен. Вдруг мы там класс '.film-details__bottom-container' изменим, логика не должна поломаться.

2021-09-03 17:55 UTC, raccoonlemon commented on src/presenter/film-details.js
> +    this._changeData(getUpdatedFilm(film, Settings.WATCH_LIST));
А почему поменяла this._film на передачу параметра? Вроде ж норм было.

2021-09-03 17:55 UTC, raccoonlemon commented on src/view/card-film.js
> +        isLongDescription: film.description > 140,
Магическое число 140. 
Лучше сделать функцию в utils/films - getShortDescription. И там рядом эту константу определить.

2021-09-03 17:56 UTC, merged

2021-09-04 04:56 UTC, Nastasiya-Kam commented on src/presenter/film-board.js
> +      });
ура_)

2021-09-04 05:04 UTC, Nastasiya-Kam commented on src/view/film-comments.js
>      </div>
а я вчера увидела, и думала, что так и нужно по макету. Подумала ещё, и кто придумал выводить смайлы через запятую...
поправила

2021-09-04 05:14 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +  }
я тоже подумала и вспомнила, что все переменные лучше держать для чтения. А запись и использование через get/set методы.

Оставила функцию как была

2021-09-04 05:18 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +    this._changeData(getUpdatedFilm(film, Settings.WATCH_LIST));
потому что при пересоздании оставался старый this._film со своими старыми isWatched, isFavorite и т.д. И при каждом клике у меня менялось что-то одно, а два других возвращались в исходное состояние

Если всё было тру, например, то при клике на первое, было всё ок. А при втором клике первое возвращалось в тру, и только второе и третье было ок и т.д.
**true** true true
false **true** true
true false true

Все клики применялись к изначальному состоянию и при новом клике происходил возврат к изначальному + клик

2021-09-04 05:24 UTC, Nastasiya-Kam commented on src/view/card-film.js
> +        isLongDescription: film.description > 140,
Я заметила, что если 140-ой символ это пробел, то в описании идёт " ...". Выглядит как-то не очень. Нужно ли сделать проверку, что если последний символ пробел, тогда не 139 символов выводить, а 138?

![image](https://user-images.githubusercontent.com/68639052/132083570-b95c7648-4f50-49c9-ab84-3dc851a74013.png)

Саму функцию вынесла в utils/films.js

2021-09-04 05:28 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +    this.renderControls(this._film);
мне кажется я начинаю понимать что и почему нужно делать_))
Поправила

2021-09-04 05:29 UTC, Nastasiya-Kam commented on src/view/card-film.js
> +  }
Да, обманула_)) у меня было такое в двух местах. Не посмотрела на название view
Теперь убрала

2021-09-04 06:28 UTC, raccoonlemon commented on src/view/card-film.js
> +        isLongDescription: film.description > 140,
Можно для обрезанной строки вызвать функцию trim - она удалит лишние пробелы.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

2021-09-04 06:34 UTC, raccoonlemon commented on src/presenter/film-details.js
> +    this._changeData(getUpdatedFilm(film, Settings.WATCH_LIST));
![image](https://user-images.githubusercontent.com/71271294/132085233-d5ec1083-1be1-42dc-8e15-7c9c8a6d6e7e.png)

У этой проблемы есть еще такое решение.
Тут сделать не метод renderControls, а типа update/refresh. 
Презентеру доски не надо знать внутреннюю кухню презентера попапа.
Он должен ему сказать - иди обновись, а что он там внутри перерендерит - его личное дело.
И когда будешь вызывать update, то первым делом в попап this._film установишь новый фильм. И уже все отрендерится как нужно, согласно новым данным.

2021-09-06 14:45 UTC, Nastasiya-Kam commented on src/view/card-film.js
> +        isLongDescription: film.description > 140,
так и сделала, спасибо

2021-09-18 06:39 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +    this.getElement().querySelector('.film-details__emoji-list').addEventListener('click', this._onEmojiClick);
вот теперь я поняла зачем нужен был change. А тогда у меня была другая логика "сборки" ссылки

2021-09-18 14:59 UTC, raccoonlemon commented
Баг с обновлением списка комментов. Удалила коммент у фильма и получилось так:
![image](https://user-images.githubusercontent.com/71271294/133893165-7965c128-a9f4-4647-b074-61666223bb21.png)

2021-09-18 15:04 UTC, raccoonlemon commented
Пощелкала несколько раз туда-сюда фильтры и сортировку, что-то со списками неладное происходит.
![image](https://user-images.githubusercontent.com/71271294/133893318-c23dd148-4306-4a54-a816-5d2a95a06fc3.png)