Module7 task2
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #13
Opened 2021-09-12 17:29 UTC by Nastasiya-Kam

Не пойму почему у меня при выборе периода диаграмма становится узкой и слипшейся + при наведении происходит скачёк, который показывает какие-то данные

![image](https://user-images.githubusercontent.com/68639052/132996989-863928ed-355f-4f23-9046-098c2b6f226b.png)

Кажется я не совсем поняла задание п.5:
> 5. Настройте выбор периода, за который нужно отобразить статистику. Графики должны обновляться при изменении периода в поле выбора периода. Неизменным остаётся только звание пользователя.
> Обратите внимание, фильтры на графики и диаграммы никак не влияют.

![image](https://user-images.githubusercontent.com/68639052/132997006-435cbbde-49ee-486b-98a1-694eeb104927.png)

Должна ли меняться сумма часов, кол-во просмотренных фильмов и любимый жанр, при изменении периода?
И какие фильтры не влияют на графики и диаграммы?
И что подразумевается под графиком, а что под диаграммой?

2021-09-13 06:12 UTC, raccoonlemon requested changes
> Не пойму почему у меня при выборе периода диаграмма становится узкой и слипшейся + при наведении происходит скачёк, который показывает какие-то данные
> 
> ![image](https://user-images.githubusercontent.com/68639052/132996989-863928ed-355f-4f23-9046-098c2b6f226b.png)
> 
> Кажется я не совсем поняла задание п.5:
> 
> > 1. Настройте выбор периода, за который нужно отобразить статистику. Графики должны обновляться при изменении периода в поле выбора периода. Неизменным остаётся только звание пользователя.
> >    Обратите внимание, фильтры на графики и диаграммы никак не влияют.
> 
> ![image](https://user-images.githubusercontent.com/68639052/132997006-435cbbde-49ee-486b-98a1-694eeb104927.png)
> 
> Должна ли меняться сумма часов, кол-во просмотренных фильмов и любимый жанр, при изменении периода?
> И какие фильтры не влияют на графики и диаграммы?
> И что подразумевается под графиком, а что под диаграммой?
> 
> 🎓 [Меняй-удаляй (часть 2)](https://up.htmlacademy.ru/ecmascript/15/user/1608929/tasks/13)
> 
> 💥 https://htmlacademy-ecmascript.github.io/1608929-cinemaddict-15/13/

В задании имеется в виду, что при выборе периода изменяется диаграмма и общие итоги. 
You watched
Total duration
Top genre

Сейчас у тебя общие итоги не пересчитываются.

То что фильтры не влияют, имеется в виду фильтры Watchlist History Favorites. Ну хотя они то и отключены, когда мы на Stats щелкаем. Видимо в задании решили на всякий случай уточнить.

Если вдруг еще какие-то непонятности по заданию - напиши в телеграм.

У меня диаграмма корреткно отображается. Очень странно. Попробуй стили проверить для нее, что там по высоте.
![image](https://user-images.githubusercontent.com/71271294/133032324-e2c5fffb-e7c2-4229-a265-f9dda9ea525a.png)

И еще заметила:

- комментарий добавляется даже если не выбран смайл. Точно не могу в ТЗ найти о необходимости проверки. Но при отправке на сервер в следующем задании скорее всего сервер не примет. Надо перед добавлением коммента добавить проверку что заполнен текст и выбран смайл. Если нет, то добавить форме shake (в 8 разделе будет пример в демо-проекте). Можно в следующем задании поправить.

- когда на фильме щелкаю isWatched, дата watchingDate не устанавливается. Надо туда записать текущую. Соответсвенно когда мы потом заходим в статистику, по фильтру Today дожно попасть то что мы вот сейчас добавили в isWatched. Нужно в текущем задании поправить.

- ты везде в моках фильмов работаешь с датами как строкой, лучше бы это был объект дата, но не критично, можно оставить. В следующем задании по работе с сервером станет понятнее, как удобнее.

2021-09-13 06:12 UTC, raccoonlemon commented on src/view/statistic.js
> +    },
Там кажется нужно еще отсортировать по убыванию.
Лучше немного иначе сделать получение данных.
Собрать сначала массив типа 
```
[
{genre: 'comedy', count: '10'}, 
{genre: 'drama', count: '12'}
...
]
```

Отсортировать его. И для диаграммы данные получить так:
```
labels = genresData.map(el=>el.genre)
data = genresData.map(el=>el.count)
```

2021-09-13 17:04 UTC, Nastasiya-Kam commented on src/utils/statistics.js
> +const makeItemsUniq = (items) => [...new Set(items)];
поправила

2021-09-13 17:05 UTC, Nastasiya-Kam commented on src/view/movies-inside.js
> +class MoviesInside extends AbstractView {
пришлось_)) я так долго думала, как эту фитюльку назвать и пришлось в итоге переименовывать...

2021-09-13 18:23 UTC, Nastasiya-Kam commented on src/utils/statistics.js
> +};
поправила

2021-09-13 18:33 UTC, Nastasiya-Kam commented on src/view/statistic.js
> +    },
Я думала, что наверное нужно ранжировать, но в ТЗ нигде этого не нашла, поэтому не реализовала. Попробую переделать

2021-09-14 04:53 UTC, Nastasiya-Kam commented on src/view/statistic.js
> +    },
переделала

2021-09-14 05:03 UTC, Nastasiya-Kam commented
![image](https://user-images.githubusercontent.com/68639052/133197619-782a9e2b-dced-4774-a47b-a572c4850042.png)
![image](https://user-images.githubusercontent.com/68639052/133197659-0ae383a0-3f7e-4a1d-a208-d6abcfd1e1c8.png)
Плюс консоль ругается, мол нужно использовать по-другому 
![image](https://user-images.githubusercontent.com/68639052/133197719-bfffd51c-b89e-424f-9808-0bccdc7564c3.png)

А в firefox всё огонь, не криво, хоть консоль и ругается
![image](https://user-images.githubusercontent.com/68639052/133197877-9ede3f43-ca5f-47b9-84d1-13e852848435.png)

2021-09-14 17:05 UTC, Nastasiya-Kam commented
Всё поправила, кроме проверки комментария и даты "строкой"

2021-09-15 03:42 UTC, raccoonlemon approved these changes
Осталось поправить тут, в константу вынести.
`if (this._renderedFilmCount % 5 !== 0) {`

А в остальном все здорово =)

![f9350960111d43d50bc801bf6a2e3b78](https://user-images.githubusercontent.com/71271294/133367046-d23519ff-5705-4200-9541-6755958e326d.jpg)

2021-09-15 03:42 UTC, raccoonlemon commented on src/view/statistic.js
> +  }
Наверное this._setChart() надо куда-то в другое место.
restoreHandlers должен заниматься только восстановлением обработчиков.

2021-09-15 03:42 UTC, raccoonlemon commented on src/utils/statistics.js
> +const makeItemsUnique = (items) => [...new Set(items)];
Функция простая, можно ее присвоить без указания авторства =)

2021-09-15 03:42 UTC, raccoonlemon commented on src/utils/statistics.js
> +};
Отличное решение =)

2021-09-15 03:42 UTC, raccoonlemon commented on src/view/statistic.js
> +  // >> Возвращаемый объект? genresData = {labels: [], data: []};
Хорошо, что ты такие вещи в todo записываешь.

2021-09-15 03:42 UTC, raccoonlemon commented on src/presenter/film-board.js
> +    if (this._renderedFilmCount % 5 !== 0) {
Вот тут не поправила, поправь пожалуйста в следующем задании.

2021-09-15 03:43 UTC, merged

2021-09-15 04:32 UTC, Nastasiya-Kam commented on src/utils/statistics.js
> +const makeItemsUnique = (items) => [...new Set(items)];
ok

2021-09-15 04:42 UTC, Nastasiya-Kam commented on src/presenter/film-board.js
> +    if (this._renderedFilmCount % 5 !== 0) {
поправила

2021-09-15 04:42 UTC, Nastasiya-Kam commented on src/view/statistic.js
> +  }
перенесла в обработчик кликов