Module8 task2
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #15
Opened 2021-09-18 13:16 UTC by Nastasiya-Kam

Вопрос по ТЗ: должна ли отрисовываться сортировка, если нет фильмов (например, установлен фильтр)

2021-09-18 13:17 UTC, Nastasiya-Kam commented on src/model/films.js
> +    const userDetails = film['user_details'];
это ошибка в наименовании? существительное во множественном числе, хотя это не массив

2021-09-18 13:21 UTC, Nastasiya-Kam commented on src/view/card-film.js
>    setOnCommentsClick(callback) {
по критерию Д8 говорится о порядке методов: сначала методы класса, потом приватные, затем обработчики

Вот у меня идёт:
_обработчик
_обработчик
установкаОбработчика
установкаОбработчика
_обработчик
установкаОбработчика
_обработчик
установкаОбработчика

Это корректно или нет?

2021-09-18 14:24 UTC, raccoonlemon commented on src/view/card-film.js
>    setOnCommentsClick(callback) {
Аа, теперь поняла, о чем вопрос был =)
Ну по критерию тогда получается должно быть так:
публичныеМетоды
установкаОбработчика
можетЕщеКакиеНибудьПубличныеМетоды
_приватныеМетоды
_обработчик

2021-09-18 14:24 UTC, raccoonlemon commented on src/model/films.js
> +    const userDetails = film['user_details'];
Если ты про userDetails, то нормально. Вроде не запрещено объекты называть во множественном числе =)

2021-09-18 15:08 UTC, raccoonlemon commented
Баг с обновлением списка комментов. Удалила коммент у фильма и получилось так
![133893165-7965c128-a9f4-4647-b074-61666223bb21](https://user-images.githubusercontent.com/71271294/133893442-61555592-b150-4eaf-8b40-b78e68ee8079.png)
:

2021-09-18 15:09 UTC, raccoonlemon commented
Пощелкала несколько раз туда-сюда фильтры и сортировку, что-то со списками неладное происходит.
![133893318-c23dd148-4306-4a54-a816-5d2a95a06fc3](https://user-images.githubusercontent.com/71271294/133893458-b1e3a9a3-bdb8-407d-9e56-38f9463e99a7.png)

2021-09-18 15:11 UTC, raccoonlemon requested changes
Пара багов со списками фильмов.
И повторный вызов апи при добавлении комментов.

А в остальном все хорошо, потестила по всякому запросы к апи - ошибки отрабатываются корректно.

И в целом я вижу ты много рефакторинга сделала, все лучше и лучше становится. И описания коммитов мне очень нравятся =)

2021-09-18 15:29 UTC, raccoonlemon commented
Вот еще идея для организации кода.
Можно с помощью комментов делать заголовки и разделять прцедуры.
![image](https://user-images.githubusercontent.com/71271294/133894067-00c3456d-94ff-4414-8fb6-24b099f0f412.png)

2021-09-19 10:21 UTC, Nastasiya-Kam commented on src/view/card-film.js
>    setOnCommentsClick(callback) {
но они же сами делали:

_обработчик
установка обработчика (т.е. бубличный метод)

везде

2021-09-19 10:52 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +  }
в трёх, в двух местах он публичный, а в третьем - частный.
Не "жирно" ли объявлять столь редкий метод для всего Abstract?
или если метод повторяется хотя бы у двоих "детей", то нужно сразу выносить в родителя, даже если используется этот метод только двумя из 50?

2021-09-19 11:00 UTC, Nastasiya-Kam commented on src/view/film-details.js
> +  }
перенесла в Abstract

2021-09-19 11:23 UTC, Nastasiya-Kam commented on src/api.js
> +  }
АААААаааа

поправила_)) вот иногда, когда в демо проекте в колбэке прописана одна строка, то страшно написать кода больше...
да и вообще сделать по-другому, а не как показано

переделала по-другому

2021-09-19 11:28 UTC, Nastasiya-Kam commented on src/model/films.js
> +    const indexFilm = this._films.findIndex((film) => film.id === filmId);
что-то пока не пойму как

2021-09-19 12:37 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +  }
инкапсулировала и убрала _setViewState

2021-09-19 12:39 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +};
я ещё это сделала до того как досмотрела видео урок, потому что у меня не обрабатывался "неуспешный" запрос. Там это выглядит как aborting, но применяется он к одному и тому же объекту. И я решила оставить так

удалила, т.к. переделала на внутренний метод класса

2021-09-19 12:41 UTC, Nastasiya-Kam commented
> Вопрос по ТЗ: должна ли отрисовываться сортировка, если нет фильмов (например, установлен фильтр)
> 
> 🎓 [Пришёл, увидел, загрузил (часть 2)](https://up.htmlacademy.ru/ecmascript/15/user/1608929/tasks/15)
> 
> 💥 https://htmlacademy-ecmascript.github.io/1608929-cinemaddict-15/15/
> 
> Я думаю, что нет.
> В разметке если список пустой, то сортировка не отрисовывается. Там правда фильтр не выбран, но я думаю, что логика будет такая же. Зачем нам фильтр, если нечего фильтровать.

Чтот этот список сортировки с самого начала мне не зашёл, вообще не выходит его рендерить, т.к. находится посередине компонента, в котором происходит вся отрисовка. Единственное, что я понимаю, это нужно каждый раз рендерить всю досту (с экстра списками), при смене фильтра, а я этого не хотела

2021-09-19 12:45 UTC, Nastasiya-Kam commented on src/presenter/profile.js
> +      remove(prevProfileComponent);
А я не помню почему оставила else. Что-то там не выходило с перерисовкой этой аватарки. Может потом переделала

2021-09-19 12:49 UTC, Nastasiya-Kam commented on src/presenter/profile.js
> +      remove(prevProfileComponent);
убрала else. Выглядит ok

2021-09-19 12:49 UTC, Nastasiya-Kam commented on src/presenter/film-details.js
> +          });
убрала запрос к серверу для комментов

2021-09-19 12:53 UTC, Nastasiya-Kam commented
> Вот еще идея для организации кода.
> Можно с помощью комментов делать заголовки и разделять прцедуры.
> Внутри *** Render *** можно еще посортировать от общего к частному, например.

Удобненько. Изначально, с первого курса, читая критерии, зашло под корку, что нельзя оставлять комментарии, что это плохо, засоряет код.

Если делать так, то тогда нужно все модули поправить по такому принципу?

2021-09-19 12:54 UTC, Nastasiya-Kam commented on src/view/statistic.js
> +      : `<p class="statistic__rank">
Это потому что использована одна и та же переменная дважды?

2021-09-19 12:59 UTC, Nastasiya-Kam commented
Мне кажется сил на _оффлайн_ у меня не осталось_))

2021-09-19 13:21 UTC, Nastasiya-Kam commented
И я удалила все комментарии у фильмов, когда тестировала

2021-09-19 14:39 UTC, raccoonlemon commented on src/view/card-film.js
>    setOnCommentsClick(callback) {
Да, возможно в демо-проекте у них не отсортировано.
Ладно, это не такой критичный критерий. Да и придраться я думаю тут сложно при проверке. Ты вроде все передвинула куда надо в итоге.

2021-09-19 14:41 UTC, raccoonlemon commented on src/model/films.js
> +    const indexFilm = this._films.findIndex((film) => film.id === filmId);
Не критично. Если останется время и желание - можем потом разобрать.

2021-09-19 14:44 UTC, raccoonlemon commented on src/view/film-details.js
> +  }
Ну правил таких нет когда и что выносить, вопрос целесообразности.
У нас есть критерий про дублирование кода - ну он тоже такой немного мутный, не всегда корректно к этому придираться.

Я бы вообще вынесла shake в тот модуль где методы render, remove. Не добавляла бы в поля класса. Но я тоже стараюсь сильно от демо-проекта не отходить там где это не особо нужно, чтобы лишний раз тебя не мучить =)

А вообще может быть много разных решений.

2021-09-19 15:08 UTC, raccoonlemon commented
> > Вот еще идея для организации кода.
> > Можно с помощью комментов делать заголовки и разделять прцедуры.
> > Внутри *** Render *** можно еще посортировать от общего к частному, например.
> 
> Удобненько. Изначально, с первого курса, читая критерии, зашло под корку, что нельзя оставлять комментарии, что это плохо, засоряет код.
> 
> Если делать так, то тогда нужно все модули поправить по такому принципу?

Я не думаю, что все надо одинаково делать. Большие удобно так оформлять. В маленьких, я думаю не требуется. В общем, если ты где-то это в одном месте это используешь, тебя ничто не обязывает делать везде одинаково, если это не несет пользы.
 
Насчет того что комментарии плохо - там есть нюансы, надо понимать почему и в каких случаях. Довольно интересная тема. В данном случае это фактически декоративный элемент, никому вреда не приносит =)

Вот неплохая статья про комментирование кода:
https://habr.com/ru/company/piter/blog/458990/

2021-09-19 15:14 UTC, raccoonlemon commented
> Мне кажется сил на _оффлайн_ у меня не осталось_))

Понимаю)) 

Для оффлайна по большей степени все из демо-проекта нам подходит. Можно все позаимствовать с мелкими совсем правками. 

Вообще ты и так огромную работу проделала. Ты молодец. Ты много всего дополнительного сделала и улучшила по сравнению с тем, если просто делать точь-в-точь по примеру демо-проекта.

Надо хоть пару денечков отдохнуть и отвлечься, может еще появятся силы доделать. Там действительно чуточка осталась.

2021-09-19 15:24 UTC, raccoonlemon approved these changes
Еееей, все самое сложное пройдено =)
![image](https://user-images.githubusercontent.com/71271294/133933111-86f07879-09cb-4f0a-a43f-c407ce697aaa.png)

2021-09-19 15:24 UTC, raccoonlemon commented on src/view/statistic.js
> +      : `<p class="statistic__rank">
Возможно, вкусовщина. Трудновато тернарный оператор в разметке читать. Не принципиально.
![image](https://user-images.githubusercontent.com/71271294/133931889-7e42f67d-848c-4d44-aff7-b08182045696.png)

2021-09-19 15:24 UTC, merged