Module2 task1
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #4
Opened 2021-08-05 04:51 UTC by Nastasiya-Kam

1. Не получилось создать структуру для фильтра (модуль filter.js)
2. Корявая вставка данных о фильтре в зависимые модули (main.js, site-menu.js)
2. Не получилось создать структуру для юзера (модуль user.js)
3. Корявая вставка данных о пользователе в зависимый модуль (profile.js)
3. Добавила для удобства закрытие попапа, чтобы работать с данными на странице
4. Добавила много закомментированного кода к открытию и закрытию попапа

2021-08-05 11:11 UTC, raccoonlemon requested changes
Не счтиая фильтров, все остальное хорошо =)

По поводу пользователя - отписалась комментарием к коду.

По фильтрам тоже - насколько могла подробно расписала как можно сделать. Но это было бы лучше на консультации вместе разобрать, если захочешь - можем запланировать. 

По фильтрам я бы еще хотела чтобы мы порефакторили темплейт, чтобы в цикле выводить разметку для фильтра и можно было установить активный фильтр через параметр, а не статично как сейчас. Тоже как идея для консультации. Но необязательно.

Из обязательного что осталось, чтобы можно было зачесть задание:
- внести правки по юзеру
- закончить фильтры

Все остальные предложения по правкам и рефакторингу необязательные.

2021-08-05 11:11 UTC, raccoonlemon commented on src/view/filter.js
> +const filmToFilterMap = {
Наверное по ошибке файл в папке view.
Его лучше перенести в utils/filter.js.

Я так понимаю, что ты хочешь получить такую структуру:
const filterFilmsCount = {
watchList: 12,
watched: 4,
favourite: 3
}

Мы можем завести перечисление:
const Filters = {watchlist: 'watchlist', watched: 'watched', favorite: 'favorite'}
(можно и обойтись без него, но оно нам еще дальше пригодится)

Дальше твоя структура filmToFilterMap со списком функций для подссчета - хорошее решение.
Но я бы внесла правку, в качестве ключей мы используем наше новое перечисление.

const filmToFilterMap = {
  [Filters.watchlist] : (films) => films.filter((film) => film.isWatchList).length,
  ...
};

И дальше примерно то же делаем, что и у тебя сейчас в функции generateFilter. Но метод map нам не подходит, потому что он вернет массив.
Мы можем сначала создать пустой объект, обойти в цикле все наши фильтры и добавить в этот объект поля с именем фильтра и значение с результатом расчета.

Вот. Если вдруг путанно и непонятно, можем на консультации вместе сделать.

2021-08-05 19:27 UTC, Nastasiya-Kam commented on src/mock/film.js
> +  isFavorite: Boolean(getRandomInteger(0, 1)),
вынесла в функцию getRandomBoolean

2021-08-05 19:29 UTC, Nastasiya-Kam commented on src/mock/film.js
> +  description: generateDescription(getRandomInteger(MIN_DESCRIPTION_COUNT, MAX_COUNT)),
В первый раз так и сделала, потом пожадничала строк в коде и "одинаковых" значений и вынесла в одно. Чувство того, что цифры могут измениться меня не переубедило

Поправила

2021-08-05 19:38 UTC, Nastasiya-Kam commented on src/mock/film.js
> +  return NAMES[getRandomInteger(0, NAMES.length - 1)];
Переделала

2021-08-05 20:19 UTC, Nastasiya-Kam commented on src/view/profile.js
> +  if (watched === 0) {
Вынесла users.js
film.js не трогала пока

2021-08-05 20:24 UTC, Nastasiya-Kam commented on src/view/statistics.js
> +const createStatisticsTemplate = (films) => `<p>${films.length} movies inside</p>`;
создала функцию в utils/films.js

2021-08-05 20:26 UTC, Nastasiya-Kam commented on src/view/profile.js
> +  if (watched === 0) {
upd: но вспомогательный модуль films.js (в директории utils) создала

2021-08-06 04:00 UTC, Nastasiya-Kam commented on src/view/filter.js
> +const filmToFilterMap = {
Невнимательно посмотрела: в учебном проекте фильтры лежат в моках (src/mock/filter.js)
Да, верно, такую структуру я и хотела получить
По перечислениям пока не понятно для чего так, но внесу его в исправления
После того как сдала на проверку стала додумывать сидеть, как переделать. Тоже пришла к решению, что нужно создать пустой объект и обойти его (forEach вместо map)

2021-08-06 04:19 UTC, Nastasiya-Kam commented on src/view/profile.js
> +const createProfileTemplate = (count) => {
сделала

2021-08-06 04:31 UTC, Nastasiya-Kam commented on src/mock/user.js
> +// const user = {
Мне кажется без какой-то поддержки переменной, при сравнении ранга для вычисления значений, появляются магические числа: 1, 10, 20. Завела перечисление для устранения "магических" значений.

Так можно или неправильно?
```
const Grades = {
  LOW: 1,
  MIDDLE: 10,
  HIGH: 20,
};
```

2021-08-06 04:41 UTC, Nastasiya-Kam commented
Если речь идёт о createSiteMenuTemplate (где watched, favorite...), я смотрела на него с точки зрения сокращения до одной строки. Но там везде разные наименования: history вместо watched, например. Вероятно нужно завести какую-то структуру соответствий. У меня со структурами пока не сложилось дружбы
`<a href="#history" class="main-navigation__item">History <span class="main-navigation__item-count">${watched}</span></a>`

Ещё смотрела на кусок кода, где таблица к фильму: Director, Actors, Release Date и т.д. (строки 55-84 view/popup.js), 
`
<table class="film-details__table">
    <tr class="film-details__row">
      <td class="film-details__term">Director</td>
      <td class="film-details__cell">${director}</td>
    </tr>
    <tr class="film-details__row">...</tr>
    ...
</table>
`
чтобы тоже сделать одной строкой, т.к. по сути строки у таблицы одинаковые и отличие только в наполнении. Когда начала делать опять-таки не сообразила как нужно реализовать структуру и вообще можно ли / нужно ли / на сколько целесообразно такое делать

2021-08-06 04:41 UTC, Nastasiya-Kam commented
Как-то не так вставился код с таблицей, как я ожидала

![image](https://user-images.githubusercontent.com/68639052/128456956-a1a087db-07a4-4b48-b008-3e5c34b3e77f.png)

2021-08-06 04:47 UTC, Nastasiya-Kam commented on src/view/filter.js
> +const filmToFilterMap = {
Перенесла в utils/filter.js
Завела перечисление Filters
Переделала фильтр

2021-08-06 05:14 UTC, raccoonlemon commented on src/mock/user.js
> +// const user = {
Да, все правильно)

Или можно еще развить идею типа такого:

![image](https://user-images.githubusercontent.com/71271294/128459383-a6c03dc4-fc7b-49ad-8ee1-6b626dab508e.png)

2021-08-06 05:17 UTC, raccoonlemon commented on src/mock/film.js
> +  description: generateDescription(getRandomInteger(MIN_DESCRIPTION_COUNT, MAX_COUNT)),
Если стоит выбор между количеством строк кода и читаемостью - читаемость у нас всегда в приоритете.
Да и в целом, меньше строк - это экономия на спичках.

2021-08-06 05:31 UTC, raccoonlemon commented
Чтобы вывести фильтры через map как вариант можно использовать или объект или массив, где будут все нужные значения, типа:
[
   {filterType: Filter.watchList
    title: 'Watch list"
    href: '#history'
    count: 12},

    {filterType: Filter.favorite
    title: 'Favorite"
    href: '#favorite'
    count: 3},
  ...
]

Еще будет возможность порефакторить фильтры в других заданиях, пока оставь как есть.

Для того что бы таблицу выводить списком - это можно похожим образом сделать, собрать массив объектов [{title, value}..]. Если хочешь потренироваться. Но я субъективно думаю, что в данном случае это не особо то и нужно, как-то нет ощущения что это какая-то однородная структура. Тут единственного правильного мнения нет, на твое усмотрение.

2021-08-06 05:33 UTC, raccoonlemon commented
Ну и в целом все здорово. Я думаю, что продуктивно поработали =)

2021-08-06 05:33 UTC, merged