Module3 task1
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #5
Opened 2021-08-08 08:10 UTC by Nastasiya-Kam

1. Компоненты реализованы через классы
2. Добавлены обработчики событий по клику на обложку, наименование и комментарии для открытия попапа
3. Добавлено открытие и закрытие попапа

2021-08-08 11:14 UTC, raccoonlemon requested changes
Все хорошо, в целом обязательных правок нет, в основном предложения по мелкому рефакторингу.
По комментам просто отпишись, еще раз отправь и я приму.

2021-08-08 11:14 UTC, raccoonlemon commented on src/view/most-commented.js
> +class MostCommented {
Вместо добавления каждого списка как отдельного компонента можно сделать FilmsList универсальным, передавать туда title и признак типа isExtraList чтобы добавлять класс films-list--extra при необходимости.
(по желанию)

2021-08-08 11:14 UTC, raccoonlemon commented on src/view/popup-comments.js
> +  constructor(film) {
Можно сюда в конструктор передавать сразу comments, если данные самого фильма никак не используются.
(не обязательно)

2021-08-08 11:14 UTC, raccoonlemon commented on src/main.js
> +  //? Не выглядит ли все три навешивания событий повторением в коде? Возможно нужно все три слушателя повесить через делегирование?
Можно попробовать сделать через делегирование.
А можно пока и отложить, этот код в дальнейшем еще попадет под рефакторинг.

2021-08-08 11:31 UTC, Nastasiya-Kam commented on src/utils/utils.js
> +const renderElement = (container, element, place) => {
Поправлю.

В целом вопрос: не теряется ли читаемость кода, когда мы начинаем использовать параметры по умолчанию. Получается они как бы "пропадают" из нашего поля видения и со временем не помним, что функция должна вообще принимать какой-то аргумент

2021-08-08 11:36 UTC, Nastasiya-Kam commented on src/utils/utils.js
> +export {getRandomInteger, getInteger, getRandomFloat, renderTemplate, RenderPosition, renderElement, createElement, isEscEvent};
Перенесу

Мучал вопрос с перечисление RenderPosition. В учебном проекте мы создали модуль const.js. Не нужно ли нам это перечисление переместить туда? На сколько я понимаю, данное перечисление мы и дальше будем использовать до конца проекта (когда уйдут моковые данные)? Либо этот модуль был создан только для констант и перечисления не входят туда?

2021-08-08 11:39 UTC, Nastasiya-Kam commented on src/utils/utils.js
> +export {getRandomInteger, getInteger, getRandomFloat, renderTemplate, RenderPosition, renderElement, createElement, isEscEvent};
Кстати, забыла, что функция renderTemplate более не используется. Я её удалю совсем

2021-08-08 11:54 UTC, Nastasiya-Kam commented on src/view/popup-comments.js
> +  constructor(film) {
Точно. Переделала

2021-08-08 13:01 UTC, Nastasiya-Kam commented on src/main.js
> +  //? Не выглядит ли все три навешивания событий повторением в коде? Возможно нужно все три слушателя повесить через делегирование?
Отложу

2021-08-08 13:38 UTC, Nastasiya-Kam commented on src/view/most-commented.js
> +class MostCommented {
Переделала

2021-08-08 16:01 UTC, raccoonlemon approved these changes
Совсем мелкие правки написала. Можно в следующих заданиях сделать, если захочется.
Этот пулреквест принимаю.

2021-08-08 16:01 UTC, raccoonlemon commented on src/main.js
> +import {renderElement, isEscEvent, TITLES} from './utils/dom.js';
TITLES скорее всего относится не к dom.js, а в какой-нибудь films.js

2021-08-08 16:02 UTC, merged

2021-08-09 05:08 UTC, Nastasiya-Kam commented on src/main.js
> +import {renderElement, isEscEvent, TITLES} from './utils/dom.js';
перенесла

2021-08-09 05:08 UTC, Nastasiya-Kam commented on public/css/main.css
> +.film-card__title:hover {
поправила