Module3 task2
htmlacademy-ecmascript/1608929-cinemaddict-15 pull request #6
Opened 2021-08-09 05:21 UTC by Nastasiya-Kam

1. Создала модуль no-film.js, но его не использовала (сразу переделала на класс FilmsListView), но пока оставила его
2. Обработчик по Esc уже был добавлен в предыдущем задании
3. Текст сообщения не зависит от фильтрации. Ещё не понимаю как это будет реализовано (показ фильмом в соответствии с фильтрацией), поэтому в функции просто предложение для состояния фильтра All

2021-08-09 07:00 UTC, raccoonlemon requested changes
Нужно переделать рендер пустого списка.

Чтобы был отдельный компонент NoFilms, если фильмов нет, то все остальные действия не выполняем, просто его рендерим в самом начале и return.

Из компонента FilmsList убрать параметр emptyList, ему об этом знать не нужно.

2021-08-09 07:00 UTC, raccoonlemon commented on src/utils/films.js
> +const TITLES = {
Наименование перечислений.
Пока все критерии не проверяю, но бросилось в глаза)
Проверь по остальным перечислениям тоже.
https://up.htmlacademy.ru/ecmascript/15/criteries#b7

2021-08-09 07:00 UTC, raccoonlemon commented on src/utils/filter.js
> +const Filters = [
Хорошее решение) 
Можно тип фильтра 'all' тоже в перечисление занести.
Лучше переименовать isCount => 'hasCount' или 'withCount'.

2021-08-09 07:00 UTC, raccoonlemon commented on src/view/films-list.js
> +  const emptyList = (isEmptyList) ? '' : '<div class="films-list__container"></div>';
Этому компонету про empty list знать не обязательно. Если у нас empty list - то этот компонент не отрисовываем вообще. Или я не совсем понимаю, для чего это сделано.. у нас же есть отдельный компонент NoFilm.

2021-08-09 07:00 UTC, raccoonlemon commented on src/view/no-film.js
> +class NoFilm {
Лучше тогда назвать NoFilms, во множественном числе.

2021-08-09 07:00 UTC, raccoonlemon commented on src/view/site-menu.js
> +  let filterTemplate = '';
О, переделала на цикл, молодец =)
Заметила, что ты такие штуки делаешь через конкатенацию строк, можно еще как вариант через map как в демопроекте.
(на твое усмотрение)

2021-08-09 10:27 UTC, Nastasiya-Kam commented on src/utils/filter.js
> +const Filters = [
Добавила. Переименовала в hasCount

2021-08-09 10:36 UTC, Nastasiya-Kam commented on src/view/site-menu.js
> +  let filterTemplate = '';
у меня вначале Filters был объектом, поэтому тут цикл. Потом я переделала структуру
Я так ещё плаваю в структурах и их методах

Переделала на map

2021-08-09 10:38 UTC, Nastasiya-Kam commented on src/view/films-list.js
> +  const emptyList = (isEmptyList) ? '' : '<div class="films-list__container"></div>';
подумала, раз у нас универсальный создатель списков, то и пустой список тоже будет он создавать. А модуль NoFilm.js он есть, потому что изначально я через него делала пустой список. А потом переделала на createFilmsListTemplate и модуль NoFilm отключила

Переделаю на отдельный модуль

2021-08-09 11:00 UTC, raccoonlemon commented on src/view/films-list.js
> +  const emptyList = (isEmptyList) ? '' : '<div class="films-list__container"></div>';
Он не то чтобы универсальный, он настраиваемый. Мы с помощью него создаем списки с разными заголовками.
А пустой список - это некая заглушка вместо списка (да, в данном случае разметка похожа, но она могла бы быть и другой, чаще так бывает для заглушек).

Есть принципы программирования SOLID.
И там буква S - Single Responsiblity - Принцип единственной ответственности.

Это о том, что класс выполняет одну определенную задачу - список фильмов нам создает контейнер куда мы фильмы выведем.
Заглушка для пустого списка - уже немного другая ответственность. А иначе у нас класс становится слишком уж умным, берет на себя много всего и становится более сложным для понимания.

2021-08-09 13:27 UTC, Nastasiya-Kam commented on src/utils/films.js
> +const TITLES = {
const Filter = {all: 'all', watchList: 'watchList', watched: 'watched', favorite: 'favorite'};

а вот это тоже считается перечислением?

2021-08-09 13:27 UTC, Nastasiya-Kam commented on src/view/no-film.js
> +class NoFilm {
переименовала

2021-08-09 16:13 UTC, raccoonlemon commented on src/utils/films.js
> +const TITLES = {
Угу, это определенно перечисление.

2021-08-09 17:46 UTC, Nastasiya-Kam commented on src/utils/films.js
> +const TITLES = {
Переделала. Некоторые наименование тоже подправила в соответствии с критериями именования

2021-08-09 18:01 UTC, Nastasiya-Kam commented
Я как-то задумалась и получился один коммит:
1. Оформила отдельный модуль (класс) для отрисовки пустого списка
2. Переименовала перечисление TITLES в Title (и внутри константы MAIN, TOP и т.д.)
3. Аналогично переименовала перечисление Filter и добавила ему ALL
4. Перечисление Grades стало Grade (единственное число)
5. Вернула настраиваемую функцию по созданию списка фильмов (убрала от туда сборку заглушки)
6. Переделала из циклов в map у createComments, createEmojiList (модуль popup-comments.js),  createGenresTemplate (popup.js) и filterTemplate (site-menu.js)

И вопрос про выполнение критерия [Б14](https://up.htmlacademy.ru/profession/react/7/ecmascript/criteries#b14): нужно ли все создания экземпляров класса перенести наверх? (в коде в комментах тоже об этом спросила)

2021-08-09 18:07 UTC, raccoonlemon approved these changes
В целом все в порядке =)
Написала пару незначительных правок.

2021-08-09 18:07 UTC, raccoonlemon commented on src/view/no-films.js
> +    return createNoFilmTemplate();
createNoFilmTemplate => createNoFilm**s**Template

2021-08-09 18:07 UTC, raccoonlemon commented on src/view/popup-comments.js
> +const createComments = (comments) => comments.map(({text, emoji, author, date}) => `<li class="film-details__comment">
Хорошо что теперь через map.
Но можно еще чуть более читаемо сделать, можно для примера посмотреть в демо-проекте файл view/filter.js.
(по желанию)

2021-08-09 18:07 UTC, merged

2021-08-11 04:28 UTC, Nastasiya-Kam commented on src/view/films-list.js
> +    return createFilmsListTemplate(this._title, this._isExtraList, this._isEmptyList);
убрала

2021-08-11 04:28 UTC, Nastasiya-Kam commented on src/view/films-list.js
> +const createFilmsListTemplate = (title, isExtraList = false) => {
перенесла

2021-08-11 04:28 UTC, Nastasiya-Kam commented on src/view/no-films.js
> +    return createNoFilmTemplate();
переименовала

2021-08-11 04:36 UTC, Nastasiya-Kam commented on src/view/popup-comments.js
> +const createComments = (comments) => comments.map(({text, emoji, author, date}) => `<li class="film-details__comment">
перенесла на отдельную строку:
.map()
и, где есть, на отдельную строку
.join();

2021-08-11 04:36 UTC, Nastasiya-Kam commented on src/main.js
> +// ?Нужно ли перенести все создания экземпляров классов наверх (критерий Б14. Объявление переменных, значение которых известно до начала работы программы)
тогда оставлю